---
title: "p8105_hw6_NL2655"
author: "Nankun"
date: "2019/11/25"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(modelr)
library(mgcv)
```

# Problem 1

## Data cleaning

```{r}
birthweight =
  read_csv("birthweight.csv") %>% 
  janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(
    babysex = as_factor(babysex),
    frace = as_factor(frace),
    malform = as_factor(malform),
    mrace = as_factor(mrace)
  )
```

## Building model

```{r}
lm_delwt = lm(bwt ~ delwt, data = birthweight)
lm_delwt %>% 
  broom::tidy()

  birthweight %>%  
  add_residuals(lm_delwt) %>% 
  add_predictions(lm_delwt) %>% 
  ggplot(aes(x = resid, y = pred)) +
  geom_violin() +
  labs(
    x = "Residual",
    y = "Prediction"
  ) +
  theme_classic()
```

*Description*

## Compare models

```{r}
set.seed(1)

#model check#
lm_main = lm(bwt ~ blength + gaweeks, data = birthweight)
lm_int = lm(bwt ~ bhead * blength * babysex, data = birthweight)


cv_df = 
  crossv_mc(birthweight, 100) %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
    ) %>% 
    mutate(lm_delwt = map(train, ~lm(bwt ~ delwt, data = .x)),
           lm_main  = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)),
           lm_int   = map(train, ~lm(bwt ~ bhead * blength * babysex, data = .x))
           ) %>% 
  mutate(rmse_delwt = map2_dbl(lm_delwt, test, ~rmse(model = .x, data = .y)),
         rmse_main  = map2_dbl(lm_main, test, ~rmse(model = .x, data = .y)),
         rmse_int   = map2_dbl(lm_int, test, ~rmse(model = .x, data = .y)))
cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```

# Problem 2

## data cleaning

```{r}
set.seed(1551)

weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

